name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Check and Release New Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Check for Version Change
#        id: check-version
#        uses: salsify/action-detect-and-tag-new-version@v1

      - name: Publish Release Notes
#        if: steps.check-version.outputs.tag
        # We can switch to a tagged version once 5.8 is published
        uses: release-drafter/release-drafter@v5
        with:
#          publish: true
#          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
